### ISSUE TITLE
There are too many cashlinks

### ISSUE THREAD

**Issue by Illuminati-0** [finndev/cash-links#134]
Given the recent issues pertaining to the cash-link bot, whether or not it is related to the number of cashlinks/blacklist entries here, a focus on the cleansing and removal of unnecessary lines should occur. Simply put, there are too many cashlinks added for the sole purpose of building up a list. We should focus on curating a list of cashlinks that actually affect the wellbeing of the forum and so on.

**Comment by 21austria** [comment]
I don't think 1600 links are too many for the bot to handle, either way, we can check if the domains blacklisted are still up and if the files hosted are still there. We can also remove the 448 carding forums and services if we don't care about preventing the spam from happening.

Anyway, blacklisting malwares is almost useless and as I said in a suggestion thread posted a week ago: the time it takes to solve hundreds of reports daily makes deleting malwares almost useless as by the time threads are deleted, malwares are either not even relevant threads anymore or they have already infected countless people.
So I think we should really think about a better way to handle malwares, perhaps make people choose why they are reporting something and therefore give priority to infected files. Or just make disinfectors a thing.

**Comment by superpitzi2** [comment]
Hi. Is there a way to talk with you on private if possible ?

Thank you

p.s: telegram: @SantiagoFMG 
Discord: SantiagoFMG#0414

thank you

**Comment by TeamIlluminati** [comment]
> I don't think 1600 links are too many for the bot to handle, either way, we can check if the domains blacklisted are still up and if the files hosted are still there. We can also remove the 448 carding forums and services if we don't care about preventing the spam from happening.
> 
> Anyway, blacklisting malwares is almost useless and as I said in a suggestion thread posted a week ago: the time it takes to solve hundreds of reports daily makes deleting malwares almost useless as by the time threads are deleted, malwares are either not even relevant threads anymore or they have already infected countless people.
> So I think we should really find a better way to handle malwares, perhaps make people choose why they are reporting something and therefore give priority to infected files. Or just make disinfectors a thing.

Agreed, blacklisting malwares is the main issue I bring in this post. It's not necessary as the attacker can simply change the host/link/filename/etc.

**Comment by finndev** [comment]
Hi,

The bot is running again, 1600 links is nothing. Feel free to send pull requests again.

Thank you for your pull requests, @Illuminati-0
